Add option to change name regex
kyngs/LibrePremium pull request #279
Opened 2024-08-06 23:07 UTC by ramide1

I tested it in my network, it is working.

2024-08-06 23:35 UTC, PadowYT2 commented on Plugin/src/main/java/xyz/kyngs/librelogin/common/listener/AuthenticListeners.java
>      @SuppressWarnings("RegExpSimplifiable") //I don't believe you
you removed the line with the regex, remove the suppression
```suggestion
```

2025-01-03 17:29 UTC, kyngs requested changes

2025-01-03 17:29 UTC, kyngs commented on Plugin/src/main/java/xyz/kyngs/librelogin/common/listener/AuthenticListeners.java
> +        Pattern namePattern = Pattern.compile(plugin.getConfiguration().get(ConfigurationKeys.ALLOWED_NICKNAME_CHARACTERS));
Pleas pre-compile the pattern and reuse it. Compiling it in each preLogin is wasteful.

2025-01-28 09:32 UTC, kyngs commented
Stale; implement this by myself.

2025-01-28 09:32 UTC, closed without merging